### ISSUE TITLE
Crash on my Playlist "(╯‵□′)╯︵┻━┻"

### ISSUE THREAD

**Issue by 123456687548** [123456687548/BetterSpotify#15]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.time.betterspotify, PID: 1416
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List eu.time.betterspotify.spotify.data.types.ResultContainer.getItems()' on a null object reference
        at eu.time.betterspotify.spotify.SpotifyApi$getPlaylistTracks$2.invoke(SpotifyApi.kt:421)
        at eu.time.betterspotify.spotify.SpotifyApi$getPlaylistTracks$2.invoke(SpotifyApi.kt:415)
        at eu.time.betterspotify.spotify.SpotifyApi.sendGetRequest$lambda-15(SpotifyApi.kt:535)
        at eu.time.betterspotify.spotify.SpotifyApi.$r8$lambda$EctXgDXA0bJbCTZn9BFUkhfvMtk(Unknown Source:0)
        at eu.time.betterspotify.spotify.SpotifyApi$$ExternalSyntheticLambda1.onResponse(Unknown Source:4)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

```
sendGetRequest(context, url, header, { response ->
            val type: Type = object : TypeToken<ResultContainer<PlaylistItem>>() {}.type
            val result = Gson().fromJson<ResultContainer<PlaylistItem>>(response, type)

            val tracks = mutableListOf<Track>()

            result.items.forEach { tracks.add(it.track) }

            trackList.addAll(tracks)
            if (result.next == null) {
                onSuccess(trackList)
            } else {
                getPlaylistTracks(context, result.next, onSuccess, onError, trackList)
            }
        }, onError)
```

response is empty

**Comment by 123456687548** [comment]
seems to be fixed?
